=== rxnzero/SimpleTest/simple.dtd
<!ELEMENT ACD_SRNO ( #PCDATA ) >

<!ELEMENT ACD_SYMB_CD ( #PCDATA ) >

<!ELEMENT ACD_YR ( #PCDATA ) >

<!ELEMENT AFCO_NO_C0003 ( #PCDATA ) >

<!ELEMENT AGNPE_NM_C0030 EMPTY >

<!ELEMENT AGNPE_PSNO EMPTY >

<!ELEMENT APL_DIS_C0003 ( #PCDATA ) >

<!ELEMENT BAS_AD ( #PCDATA ) >

<!ELEMENT BAS_AD_1 EMPTY >

<!ELEMENT BK_CD_C0002 ( #PCDATA ) >

<!ELEMENT BK_CD_C0002_1 ( #PCDATA ) >

<!ELEMENT BRNO ( #PCDATA ) >

<!ELEMENT CORT_APL_MNG_NO ( #PCDATA ) >

<!ELEMENT CORT_CD ( #PCDATA ) >

<!ELEMENT CORT_JP_NO ( #PCDATA ) >

<!ELEMENT CORT_RCP_KD_CD ( #PCDATA ) >

<!ELEMENT CORT_TRN_DIS_CD ( #PCDATA ) >

<!ELEMENT CTN_PRC_C0021 EMPTY >

<!ELEMENT C_TR_CD EMPTY >

<!ELEMENT DEPT_CD_C0002 ( #PCDATA ) >

<!ELEMENT DISP_PSS_NO ( #PCDATA ) >

<!ELEMENT DPS_AM_SYS_DIS_C0001 EMPTY >

<!ELEMENT DTL_AD_C0150 EMPTY >

<!ELEMENT DTL_AD_C0150_1 EMPTY >

<!ELEMENT FOUT_MSG_RSP_CD ( #PCDATA ) >

<!ELEMENT KEP_CORKEPERON2002_HDR ( C_TR_CD, APL_DIS_C0003, MSG_KD_C0004, TRN_KD_C0004, SRM_DIS_C0001, MSG_MNG_NO_C0007, TMS_DY_C0008, TMS_TM_C0006, BK_CD_C0002, AFCO_NO_C0003, TRN_DIS_CD_C0003, ORGTR_MSG_NO_C0007, SM_CN_C0001, FOUT_MSG_RSP_CD, RSP_MSG_TXT, CTN_PRC_C0021, SVR_USE_C0004, SMSGPE_ID_C0010, RCVER_ID_C0010, SAF_PRC_YN, SVR_DIS_C0001, DPS_AM_SYS_DIS_C0001, CORT_TRN_DIS_CD, SPAR_C0007, CORT_CD, ACD_YR, ACD_SYMB_CD, ACD_SRNO, DEPT_CD_C0002, CORT_JP_NO, PRG_YR_C0004, PRG_SRNO_C0006, PI_AM_C0015, CORT_RCP_KD_CD, PI_DY_C0008, PAYPE_NM_C0030, PAYPE_PSNO, TEL_NO_C0012, ZIP_CD_C0007, BAS_AD, DTL_AD_C0150, AGNPE_NM_C0030, AGNPE_PSNO, TEL_NO_C0012_1, ZIP_CD_C0007_1, BAS_AD_1, DTL_AD_C0150_1, BK_CD_C0002_1, BRNO, CORT_APL_MNG_NO, RFN_BK_CD, RFN_ACT_NO_C0016, DISP_PSS_NO, KOR_NM_C0026 ) >

<!ELEMENT KOR_NM_C0026 EMPTY >

<!ELEMENT MSG_KD_C0004 ( #PCDATA ) >

<!ELEMENT MSG_MNG_NO_C0007 ( #PCDATA ) >

<!ELEMENT ORGTR_MSG_NO_C0007 ( #PCDATA ) >

<!ELEMENT PAYPE_NM_C0030 ( #PCDATA ) >

<!ELEMENT PAYPE_PSNO ( #PCDATA ) >

<!ELEMENT PI_AM_C0015 ( #PCDATA ) >

<!ELEMENT PI_DY_C0008 ( #PCDATA ) >

<!ELEMENT PRG_SRNO_C0006 ( #PCDATA ) >

<!ELEMENT PRG_YR_C0004 ( #PCDATA ) >

<!ELEMENT RCVER_ID_C0010 EMPTY >

<!ELEMENT RFN_ACT_NO_C0016 EMPTY >

<!ELEMENT RFN_BK_CD ( #PCDATA ) >

<!ELEMENT RSP_MSG_TXT EMPTY >

<!ELEMENT SAF_PRC_YN EMPTY >

<!ELEMENT SMSGPE_ID_C0010 EMPTY >

<!ELEMENT SM_CN_C0001 ( #PCDATA ) >

<!ELEMENT SPAR_C0007 EMPTY >

<!ELEMENT SRM_DIS_C0001 ( #PCDATA ) >

<!ELEMENT SVR_DIS_C0001 EMPTY >

<!ELEMENT SVR_USE_C0004 EMPTY >

<!ELEMENT TEL_NO_C0012 ( #PCDATA ) >

<!ELEMENT TEL_NO_C0012_1 EMPTY >

<!ELEMENT TMS_DY_C0008 ( #PCDATA ) >

<!ELEMENT TMS_TM_C0006 ( #PCDATA ) >

<!ELEMENT TRN_DIS_CD_C0003 ( #PCDATA ) >

<!ELEMENT TRN_KD_C0004 ( #PCDATA ) >

<!ELEMENT ZIP_CD_C0007 ( #PCDATA ) >

<!ELEMENT ZIP_CD_C0007_1 EMPTY >

=== rxnzero/SimpleTest/simple.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE KEP_CORKEPERON2002_HDR SYSTEM "simple.dtd" >
<KEP_CORKEPERON2002_HDR>
  <C_TR_CD/>
  <APL_DIS_C0003>APL_DIS_C0003</APL_DIS_C0003>
  <MSG_KD_C0004>MSG_KD_C0004</MSG_KD_C0004>
  <TRN_KD_C0004>TRN_KD_C0004</TRN_KD_C0004>
  <SRM_DIS_C0001>SRM_DIS_C0001</SRM_DIS_C0001>
  <MSG_MNG_NO_C0007>MSG_MNG_NO_C0007</MSG_MNG_NO_C0007>
  <TMS_DY_C0008>TMS_DY_C0008</TMS_DY_C0008>
  <TMS_TM_C0006>TMS_TM_C0006</TMS_TM_C0006>
  <BK_CD_C0002>BK_CD_C0002</BK_CD_C0002>
  <AFCO_NO_C0003>AFCO_NO_C0003</AFCO_NO_C0003>
  <TRN_DIS_CD_C0003>TRN_DIS_CD_C0003</TRN_DIS_CD_C0003>
  <ORGTR_MSG_NO_C0007>ORGTR_MSG_NO_C0007</ORGTR_MSG_NO_C0007>
  <SM_CN_C0001>SM_CN_C0001</SM_CN_C0001>
  <FOUT_MSG_RSP_CD>FOUT_MSG_RSP_CD</FOUT_MSG_RSP_CD>
  <RSP_MSG_TXT/>
  <CTN_PRC_C0021/>
  <SVR_USE_C0004/>
  <SMSGPE_ID_C0010/>
  <RCVER_ID_C0010/>
  <SAF_PRC_YN/>
  <SVR_DIS_C0001/>
  <DPS_AM_SYS_DIS_C0001/>
  <CORT_TRN_DIS_CD>CORT_TRN_DIS_CD</CORT_TRN_DIS_CD>
  <SPAR_C0007/>
  <CORT_CD>CORT_CD</CORT_CD>
  <ACD_YR>ACD_YR</ACD_YR>
  <ACD_SYMB_CD>ACD_SYMB_CD</ACD_SYMB_CD>
  <ACD_SRNO>ACD_SRNO</ACD_SRNO>
  <DEPT_CD_C0002>DEPT_CD_C0002</DEPT_CD_C0002>
  <CORT_JP_NO>CORT_JP_NO</CORT_JP_NO>
  <PRG_YR_C0004>PRG_YR_C0004</PRG_YR_C0004>
  <PRG_SRNO_C0006>PRG_SRNO_C0006</PRG_SRNO_C0006>
  <PI_AM_C0015>PI_AM_C0015</PI_AM_C0015>
  <CORT_RCP_KD_CD>CORT_RCP_KD_CD</CORT_RCP_KD_CD>
  <PI_DY_C0008>PI_DY_C0008</PI_DY_C0008>
  <PAYPE_NM_C0030>PAYPE_NM_C0030</PAYPE_NM_C0030>
  <PAYPE_PSNO>PAYPE_PSNO</PAYPE_PSNO>
  <TEL_NO_C0012>TEL_NO_C0012</TEL_NO_C0012>
  <ZIP_CD_C0007>ZIP_CD_C0007</ZIP_CD_C0007>
  <BAS_AD>BAS_AD</BAS_AD>
  <DTL_AD_C0150/>
  <AGNPE_NM_C0030/>
  <AGNPE_PSNO/>
  <TEL_NO_C0012_1/>
  <ZIP_CD_C0007_1/>
  <BAS_AD_1/>
  <DTL_AD_C0150_1/>
  <BK_CD_C0002_1>BK_CD_C0002_1</BK_CD_C0002_1>
  <BRNO>BRNO</BRNO>
  <CORT_APL_MNG_NO>CORT_APL_MNG_NO</CORT_APL_MNG_NO>
  <RFN_BK_CD>RFN_BK_CD</RFN_BK_CD>
  <RFN_ACT_NO_C0016/>
  <DISP_PSS_NO>DISP_PSS_NO</DISP_PSS_NO>
  <KOR_NM_C0026/>
</KEP_CORKEPERON2002_HDR>
